version: '3.8'

services:
  db:
    container_name: heaven_db
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test

  db-admin:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://root:test@db:27017/

  api:
    container_name: heaven_api
    build: ./api
    command: tail -f /dev/null
    ports:
      - 3001:9091
    volumes:
      - ./api:/app
    depends_on:
      - db

  proxy:
    container_name: heaven_proxy
    image: nginx
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
      - ./proxy/nginx.conf:/tmp/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - api